application: fabriqueapp
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: index.php

- url: /item
  script: item.php

- url: /products
  script: products.php

- url: /redirect
  script: redirect_checkout.php

- url: /stylesheets
  static_dir: stylesheets
